--Write your insert queries below
--|  id   | brand       | year_of_manufacture | color        | weight  | secondhand |
--|-------|-------------|---------------------|--------------|---------|------------|
--|  1    | Bentley     | 1988                | red metallic | 1002.72 | false      |
--|  2    | Suzuki      | 2002                | silver       | 1787.25 | true       |
