INSERT INTO address (street, number, city, zip_code, country) values ('Holy Cross', 21, 'Villeneuve-d', '59-652', 'France');
INSERT INTO address (street, number, city, zip_code, country) values ('Tomscot', 3, 'Newtown', 'RG20', 'United Kingdom');
INSERT INTO address (street, number, city, zip_code, country) values ('Kenwood', 92, 'Oklahoma City', '73-167', 'United States');
INSERT INTO users (nickname, email, gender, address_id) values ('Linda', 'lhicks0@infoseek.co.jp', 'Female', 2);
INSERT INTO users (nickname, email, gender, address_id) values ('Gerald', 'gfreeman1@parallels.com', 'Male', 3);
INSERT INTO users (nickname, email, gender, address_id) values ('Randy', 'rgeorge2@moonfruit.com', 'Male', 1);
INSERT INTO users (nickname, email, gender, address_id) values ('Benjamin', 'bbailey9@blinklist.com', 'Male', 3);
INSERT INTO product (name, description, price, user_id) values ('Lenovo ThinkCentre Chromebox Tiny Desktop', 'scelerisque sed', 147.27, 2);
INSERT INTO product (name, description, price, user_id) values ('Dell Precision Tower 5810', 'Lorem ipsum dolor sit amet', 99.08, 2);
INSERT INTO product (name, description, price, user_id) values ('Apple iMac 27-Inch With Retina 5K Display', 'in interdum massa nibh nec erat.', 212.10, 1);
INSERT INTO product (name, description, price, user_id) values ('Dell Optiplex 9020 Micro', 'sed posuere libero dui id orci. Nam congue', 58.82, 2);
INSERT INTO product (name, description, price, user_id) values ('HP Z840 Workstation', 'Etiam sit amet lectus quis est congue mollis', 33.55, 3);
INSERT INTO orders (order_date, user_id, product_id) values ('2016-05-01', 1, 5);
INSERT INTO orders (order_date, user_id, product_id) values ('2016-07-13', 1, 2);
INSERT INTO orders (order_date, user_id, product_id) values ('2016-02-11', 4, 4);
INSERT INTO orders (order_date, user_id, product_id) values ('2016-03-11', 4, 1);
INSERT INTO assessment(rating, comment, user_id, product_id) values (5, 'Lorem ipsum dolor sit amet consectetur adipiscing elit', 2, 5);
INSERT INTO assessment(rating, comment, user_id, product_id) values (5, 'Proin nibh augue suscipit a scelerisque sed lacinia in mi', 1, 5);
INSERT INTO assessment(rating, comment, user_id, product_id) values (4, 'Cras vel lorem. Etiam pellentesque aliquet tellus', 4, 3);
