DELETE FROM breed;

INSERT INTO breed("name", "family", "origin", "original_function", "male_height_min","male_height_max", "male_weight_min", "male_weight_max", "female_height_min","female_height_max", "female_weight_min","female_weight_max", "other_names", "temperament") VALUES
('Akita', 'spitz, northern (hunting)', 'Japan', 'large game hunting, dog fighting', 25,28,  85,130, 23,26, 65,110, 'Akita Inu, Japanese Akita', 'As befitting his spitz-like heritage, the Akita is bold, independent, stubborn and tenacious. Demonstrative to his family and friend, he is utterly devoted and will protect family members. Though not the breed for everyone, in the right hands the Akita is an excellent companion.'),
('American Cocker Spaniel', 'gundog, spaniel', 'United States', 'bird flushing and retrieving', 14.5,15.5,  24,28, 13.5,14.5, 24,28, 'Cocker Spaniel', 'This breed is known as the ''merry'' Cocker, and the name is most fitting. He is playful, cheerful, amiable, sweet, sensitive, willing to please and responsive to his family''s wishes. He is not known for retaining his hunting instincts, but is inquisitive and will appreciate a country outing. He is equally at home in the city and will happily walk on leash for his exercise needs. Some bark a lot; some are overly submissive.'),
('Beagle', 'scenthound', 'England', 'trailing rabbits', 13, 15,  18,30, 13,15, 18,30, 'English beagle', 'Everybody''s friend. Family dog. One of the most amiable hounds, the Beagle was bred as a pack hunter and needs companionship, whether human or canine. He loves to explore the outdoors and is an enthusiastic trailer. Given adequate exercise, he is a calm, tractable house pet. He is an excellent child''s dog, gentle, incredibly tolerant and always ready to join in a game or an adventure. He is an independent breed, however, and may run off if a trail beckons. He barks and howls.'),
('Boxer', 'livestock dog, mastiff (bulldog)', 'Germany', 'bullbaiting, guardian', 22.5,25,  65,80, 21,23.5, 50,65, NULL, 'The boxer is playful, exuberant, inquisitive, attentive, demonstrative, devoted and outgoing; he is a perfect companion for an active family. He can be stubborn, but he is sensitive and responsive to commands. He is generally good with other household dogs and pets.'),
('Bull Terrier', 'terrier, mastiff (bull)', 'England', 'dog fighting', 21,22,  55,65, 21,22, 45,55, 'English bull terrier', 'Exuberant, comical, playful, assertive and very mischievous describes the bull terrier. He is an imaginative breed that often sees things his own way and is stubborn to the end. He needs daily physical and mental exercise lest he exercise his powerful jaws on your home. For all his tough bravado, this is an extremely sweet-natured, affectionate and devoted breed.'),
('Chihuahua', 'companion, southern (pariah)', 'Mexico', 'ceremonial', 6,9, 6,6, 6,9, 6,6, NULL, 'The saucy Chihuahua has earned her place as a favored toy dog because of her intense devotion to a single person. She is reserved with strangers but good with other household dogs and pets. Some try to be protective, but they are not very effective. Some may be quite bold; others may be timid. She is often temperamental. Some bark.'),
('Chow Chow', 'spitz, northern (companion)', 'China', 'guardian, cart puller, food source', 17,20, 45,70, 17,20, 45,70, NULL, 'Dignified, even lordly, the chow chow conducts himself with reserve. He is not very demonstrative, even with his family, and can be somewhat suspicious of strangers. He is independent and stubborn and is generally good with other household pets. The Chow Chow is serious and protective, devoted to his family.'),
('Collie', 'livestock, herding', 'Scotland', 'sheep herding', 24,26,  60,75, 22,24, 50,65, 'Scottish collie', 'The Collie is gentle and devoted, a mild-mannered friend to all. He is a dog with a working heritage, and needs daily mental and physical exercise or he can become frustrated. He is sensitive, intelligent and willing to please, although he is sometimes a bit stubborn. He can nip at heels in play. Some may bark a lot.'),
('Newfoundland', 'livestock dog, sheepdog', 'Canada', 'all-purpose water dog and fishing aid, draft', 28,28,  130,150, 26,26, 100,120, NULL, 'The most important single characteristic of the Newfoundland is sweetness of temperament. The Newfoundland is calm, patient, easygoing, gentle and amiable, a friend to all. If her family is threatened, however, the Newfoundland can act protectively.');
